# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand
from strategic.models import PorterForce

# منبع: فایل «ورودی_سیستم.xlsx» — شیت porter (۳۱ عامل واقعی، همون قاعده‌ی PESTEL:
# جایگزینی کامل داده‌ی قبلی؛ میانگین/فراوانی وارد نشدند؛ فیلدهای قدیمی
# (احتمال/عدم‌قطعیت/افق/روند) روی مقدار پیش‌فرض خنثی می‌مانند تا کاربر بعداً دستی پر کند.

ROWS = [
    {'force': 'buyer_power', 'text': 'افزایش گرایش مشتری به قطعات جایگزین بین قطعه اصلی و غیر اصلی صرفاً بدلیل قیمت پایین', 'detailed_description': 'افزایش مستقیم قیمت تمام‌شده قطعات وارداتی و فشار مضاعف بر قیمت‌گذاری.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'افزایش بهای تمام‌شده قطعات'},
    {'force': 'buyer_power', 'text': 'سهولت در دسترسی به استعلام قیمت از بازار', 'detailed_description': 'اختلال در عملیات شبکه، کاهش مراجعه مشتری و افزایش ریسک عملیاتی.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'اختلال فروش و عملیات شبکه'},
    {'force': 'buyer_power', 'text': 'ارائه قطعه/خدمات(اجرت – بسته خدمت) با کیفیت تر و با قیمت مناسب به خریداران توسط سایر تامین کنندگان', 'detailed_description': 'مقایسه مستمر سطح قیمت و کیفیت خدمات شبکه با سایر فعالان بازار از سوی مشتریان که بر ارزیابی شاخص های رضایت مندی و نرخ وفاداری مشتریان اثر مستقیم می گذارد.', 'related_standard': '10004', 'effect_type': 'threat', 'scoring_guide': 'هزینه انطباق زیست‌محیطی'},
    {'force': 'buyer_power', 'text': 'سهولت خرید بواسطه ورود پلتفرم ها و استارت آپهای آنلاین', 'detailed_description': 'تغییر انتظارات و سنجه های رضایت مندی مشتریان بسمت خرید اسان،شفافیت و قیمت گذاری و سرعت دسترسی از طرق درگاههای دیجیتال و انلاین.', 'related_standard': '10004', 'effect_type': 'threat', 'scoring_guide': 'پیچیدگی تأمین و کنترل کیفیت'},
    {'force': 'buyer_power', 'text': 'افزایش تمایل مشتریان به تحویل سریع قطعات', 'detailed_description': 'اهمیت بالای زمان انتظار مشتری و تحویل بموقع قطعه بعنوان یکی از شاخص های حیاتی سنجش و پایش رضایت مشتریان.', 'related_standard': '10004', 'effect_type': 'both', 'scoring_guide': 'هزینه انطباق در برابر اعتماد'},
    {'force': 'buyer_power', 'text': 'ورود برندهای جدید الورود قطعات یدکی به بازار', 'detailed_description': 'تشدید رقابت در بازار و تنوع گزینه های پیش روی مشتریان،که ضرورت پایش مستمر رضایت مشتریان حفظ وفاداری و بهبود کیفیت شبکه را دوچندان می کند.', 'related_standard': '10004', 'effect_type': 'threat', 'scoring_guide': 'فاصله توان شبکه با انتظار مشتری'},
    {'force': 'buyer_power', 'text': 'کاهش خریداران بدلیل نبود تضمین گارانتی قطعات تجاری', 'detailed_description': 'بی اعتمادی مشتریان به کیفیت قطعات بدون گارانتی و افزایش ریسک خرابی،که زمینه ساز بروز نارضایتی شدید و ثبت شکایات  متوالی از خدمات پس از فروش می گردد.', 'related_standard': '10002', 'effect_type': 'threat', 'scoring_guide': 'میزان وابستگی و نبود جایگزین'},
    {'force': 'buyer_power', 'text': 'عدم تطابق اعتبار عوامل فروش قطعه شبکه با بدهی (موضوع اجرایی درون سازمانی)', 'detailed_description': 'ایجاد ناهماهنگی های مالی در توزیع قطعات،توقف عرضه قطعه به عاملیت ها و در نهایت شکل گیری شکایات مشتریان بدلیل عدم دسترسی به قطعات در شبکه فروش.', 'related_standard': '10002', 'effect_type': 'threat', 'scoring_guide': 'سرعت نوآوری رقبا'},
    {'force': 'buyer_power', 'text': 'سهولت فرآیند برگشت از خرید قطعات (موضوع درون سازمانی)', 'detailed_description': 'کاهش دفعات خرید و افت حجم فروش قطعات.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'کاهش حجم فروش'},
    {'force': 'supplier_power', 'text': 'نقش تأمین‌کنندگان', 'detailed_description': 'تامین بموقع قطعات در بازار بمنظور جلوگیری از شکایات در خصوص خواب خودرو و کسری کالا،و همچنین حفظ یا افزایش رضایت مشتریان خواهد شد.', 'related_standard': '10002و10004', 'effect_type': 'threat', 'scoring_guide': 'اثر بر هزینه واردات و همکاری خارجی'},
    {'force': 'supplier_power', 'text': 'رغبت داشتن تامین کنندگان گروه برای ورود به حوزه فروش مستقیم قطعات', 'detailed_description': 'کاهش یا افزایش تقاضا برای قطعات اصلی و خدمات رسمی؛ شاخص مهم جهت پیش‌بینی فروش.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'شدت کاهش تقاضای خدمات و قطعات رسمی'},
    {'force': 'supplier_power', 'text': 'پایبندی به تعهدات مالی (نظم پرداختی)', 'detailed_description': 'کاهش تمایل مشتریان به مراجعه به شبکه رسمی و حرکت به سمت بازار غیررسمی،افزایش ریسک عدم تامین قطعات و بروز شکایات مشتریان.', 'related_standard': '10002و10004', 'effect_type': 'threat', 'scoring_guide': 'میزان ریزش مشتری از شبکه رسمی'},
    {'force': 'supplier_power', 'text': 'محدود بودن تولیدکنندگان داخلی با کیفیت', 'detailed_description': 'بهبود پیش‌بینی تقاضا، مدیریت موجودی و شخصی‌سازی خدمات.', 'related_standard': '', 'effect_type': 'opportunity', 'scoring_guide': 'بهبود تصمیم‌گیری و عملیات'},
    {'force': 'supplier_power', 'text': 'عدم ارائه خدمات/قطعات بصورت اعتباری از سوی تامین کنندگان', 'detailed_description': 'ایجاد محدودیت های مالی و نقدینگی در تامین بموقع قطعات،که منجر به افزایش خواب خودرو، عدم پاسخگویی بموقع به مشتریان و در نتیجه بروز شکایات و  افت سطح رضایت انان  میشود.', 'related_standard': '10002و10004', 'effect_type': 'threat', 'scoring_guide': 'شدت تنوع برند و رقابت'},
    {'force': 'supplier_power', 'text': 'تمایل به سرمایه گذاری در بخش خدمات به بخش خصوصی', 'detailed_description': 'تصمیم‌گیری سریع رقبا، فرصت‌های بازار را محدود می‌کند.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'سرعت واکنش رقبا'},
    {'force': 'substitutes', 'text': 'کاهش سهم بازار و سود حاصل از فروش قطعه و خدمات و افزایش هزینه های سربار و خدماتی', 'detailed_description': 'افزایش هزینه تأمین مالی، کاهش جذابیت سرمایه‌گذاری و محدود شدن نقدینگی برای توسعه شبکه خدمات.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'فشار بر نقدینگی و سرمایه‌گذاری'},
    {'force': 'substitutes', 'text': 'خدمات غیررسمی تعمیرگاهی و قطعه‌فروشان آنلاین/بازارهای دیجیتال', 'detailed_description': 'خروج بخشی از تقاضای خدمات و قطعات از شبکه رسمی بدلیل سهولت دسترسی و قیمت،افزایش احتمال ورود قطعات تقلبی و بروز شکایات کیفی مشتریان .', 'related_standard': '10002و10005', 'effect_type': 'opportunity', 'scoring_guide': 'نقش برند در نگهداشت مشتری'},
    {'force': 'substitutes', 'text': 'خواسته‌ها و ملاحظات سایپا به عنوان شرکت مادر', 'detailed_description': 'نیاز به ارتقای شایستگی،اموزش مستمر پرسنل و همراستا سازی فرایندهای خدمت رسانی با الزامات و استانداردهای ابلاغی شرکت مادر', 'related_standard': '10015', 'effect_type': 'threat', 'scoring_guide': 'کمبود نیروی متخصص آینده'},
    {'force': 'substitutes', 'text': 'جایگزین شدن قطعات غیراصلی/دست دوم در شرایط تورمی بالا', 'detailed_description': 'افزایش ریسک خرابی زودرس،کاهش ایمنی و عملکرد خودور بدلیل استفاده از قطعات نامرغوب،که نهایتاً منجر به بروز شکایات کیفی مشتریان و نارضایتی از خدمات پس از فروش میگردد.', 'related_standard': '10002', 'effect_type': 'threat', 'scoring_guide': 'افزایش هزینه و الزامات فنی'},
    {'force': 'substitutes', 'text': 'افزایش تقاضا برای خودروهای برقی و هیبریدی بطور قابل توجه برای دوستداران زیست محیطی', 'detailed_description': 'پاسخگویی به انتظارات زیست محیطی جامعه از طریق توسعه خدمات پاک،کاهش آلایندگی های کارگاهی و ارتقای جنبه های زیست محیطی سازمان.', 'related_standard': '140001', 'effect_type': 'threat', 'scoring_guide': 'شدت کاهش مزیت رقابتی'},
    {'force': 'new_entrants', 'text': 'تمایل مشتریان به خرید از برندهای جدید و بهره مند شدن از خدمات آنها(عدم وفاداری مشتری و عدم نگهداشت مشتری توسط برند)', 'detailed_description': 'تغییر انتظارات از خدمات (سرعت، دیجیتال بودن، قیمت) افت و وفادار و احتمال ریزش مشتریان بسمت برندهای رقیب به دلیل عدم نگهداشت مناسب .', 'related_standard': '10002و10004', 'effect_type': 'both', 'scoring_guide': 'نیاز به بازطراحی تجربه مشتری'},
    {'force': 'new_entrants', 'text': 'عرضه قطعات غیراصلی (قاچاق یا تولید داخل)', 'detailed_description': 'تغییر ماهیت قطعات مصرفی و خدمات پس از فروش؛ هم تهدید و هم فرصت جدید.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'تغییر مدل خدمات و قطعات'},
    {'force': 'new_entrants', 'text': 'نرخ سرمایه‌گذاری در صنعت', 'detailed_description': 'هزینه اولیه بالا ولی اثر مثبت بلندمدت بر پایداری و برند.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'هزینه اولیه در برابر پایداری'},
    {'force': 'new_entrants', 'text': 'ورود بازیگران محلی کوچک و کارگاه‌های تولید قطعات غیراصلی', 'detailed_description': 'رشد هزینه‌های عملیاتی و فشار بر حاشیه سود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'فشار بر هزینه‌های عملیاتی'},
    {'force': 'new_entrants', 'text': 'جذب عوامل توسط تازه واردان به صنعت خودرو', 'detailed_description': 'افزایش شفافیت بازار و کاهش قاچاق (فرصت برای برند رسمی).', 'related_standard': '', 'effect_type': 'opportunity', 'scoring_guide': 'کاهش قاچاق و تقلب'},
    {'force': 'new_entrants', 'text': 'سهولت ورود رقبای جدید به بازار با مدل کسب و کارهای نوین و فناورانه همراه با ارائه خدمات با کیفیت تر و کاهش حاشیه سود', 'detailed_description': 'افزایش شفافیت مالی و هزینه‌های اجرایی.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'شفافیت همراه با هزینه اجرایی'},
    {'force': 'rivalry', 'text': 'رفتار رقبا', 'detailed_description': 'کاهش ریسک سیاسی، بهبود دسترسی به فناوری و قطعات باکیفیت، تسهیل سرمایه‌گذاری و امکان توسعه پایدار کسب‌وکار.', 'related_standard': '', 'effect_type': 'opportunity', 'scoring_guide': 'میزان کاهش ریسک و گشایش کسب‌وکار'},
    {'force': 'rivalry', 'text': 'واردات قطعات به بازار ایران با قیمت مناسب و کمترین زمان', 'detailed_description': 'گرایش به تعمیر حداقلی یا قطعات ارزان‌تر که سهم بازار قطعات اصلی را تهدید می‌کند.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'گرایش به قطعات ارزان/غیراصلی'},
    {'force': 'rivalry', 'text': 'رقبای ارائه دهنده خدمات/قطعات بصورت اعتباری و اقساط', 'detailed_description': 'افزایش حساسیت مشتریان به اصالت قطعه و کیفیت خدمات؛ فرصت برای برندهای معتبر.', 'related_standard': '', 'effect_type': 'opportunity', 'scoring_guide': 'تمایزپذیری برند و قطعه اصلی'},
    {'force': 'rivalry', 'text': 'واکنش رقبای چابک نسبت به شرایط محیطی', 'detailed_description': 'اثر سریع بر تصویر برند و تصمیم خرید مشتریان؛ نیازمند پایش مستمر.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'شدت اثر بر تصویر برند'},
    {'force': 'rivalry', 'text': 'ارائه خدمات جانبی به تامین کننده (نظیر همکاری در تهیه تست ریپورت ها)', 'detailed_description': 'ضعف مالی برخی نمایندگی‌ها باعث اختلال خدمت‌رسانی و لطمه به اعتبار کل شبکه می‌شود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'اثر بر انسجام شبکه فروش'},
]


class Command(BaseCommand):
    help = "تحلیل پنج نیروی پورتر سایپا یدک را با نسخه‌ی نهایی (۳۱ ردیف واقعی) پاک و جایگزین می‌کند."

    def handle(self, *args, **options):
        PorterForce.objects.all().delete()
        for order, row in enumerate(ROWS):
            PorterForce.objects.create(order=order, **row)
        self.stdout.write(self.style.SUCCESS(f"ثبت شد: {len(ROWS)} عامل Porter."))
