# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand
from strategic.models import PestelFactor

# منبع: فایل «ورودی_سیستم.xlsx» — شیت pestel (۳۸ عامل واقعی، طبق تصمیم صریح کاربر:
# جایگزینی کامل داده‌ی قبلی؛ ستون‌های میانگین/فراوانی عمداً وارد نشدند (طبق تصمیم کاربر).
# فیلدهای قدیمی (احتمال/عدم‌قطعیت/افق/روند) روی مقدار پیش‌فرض خنثی مدل می‌مانند تا کاربر بعداً دستی پر کند.
this_command_deletes_all_existing_pestel_data = True

ROWS = [
    {'category': 'political', 'text': 'ارتباطات بین‌المللی (تحریم، جنگ، ارتباطات منطقه ای)', 'detailed_description': 'تغییر نقش دولت، افزایش رقابت‌پذیری، احتمال تغییر مالکیت و سیاست‌های قیمت‌گذاری که می‌تواند ساختار زنجیره تأمین و شبکه خدمات را دچار تحول کند.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'شدت تغییر در ساختار رقابت و زنجیره ارزش'},
    {'category': 'political', 'text': 'تحریم‌ها', 'detailed_description': 'افزایش نااطمینانی، اختلال در زنجیره تأمین، نوسان شدید ارز و کاهش تقاضای بازار؛ اثر منفی مستقیم بر برنامه‌ریزی بلندمدت و سرمایه‌گذاری.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'سطح نا اطمینانی کلان و اختلال عملیاتی'},
    {'category': 'political', 'text': 'مذاکره و توافق با امریکا و اتحادیه اروپا و کاهش تنش رشد و توسعه کسب و کا', 'detailed_description': 'کاهش توان فنی و نوآوری در سطح گروه و وابستگی بیشتر به منابع محدود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'افت توان تخصصی و نوآوری'},
    {'category': 'political', 'text': 'تغییرات ساختاری صنعت خودروسازی (خصوصی‌سازی/ادغام)', 'detailed_description': 'امکان مقایسه لحظه‌ای قیمت‌ها، وفاداری مشتری را کاهش داده و چانه‌زنی را تشدید می‌کند.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'گستردگی مقایسه قیمت'},
    {'category': 'political', 'text': 'تغییرات مراودات با کشورهای منطقه‌ای و بین‌المللی (تعرفه 25%اعلامی آمریکا)', 'detailed_description': 'تشدید رقابت قیمتی در سطح خرد و کاهش حاشیه سود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'پراکندگی رقبا'},
    {'category': 'economic', 'text': 'حذف ارز نیمایی و الزام به تامین ارز تک نرخی( تالار دوم)', 'detailed_description': 'اختلال در تولید، انبارداری و ارائه خدمات شبکه.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'اختلال در تولید و خدمات'},
    {'category': 'economic', 'text': 'نرخ بالای بهره بانکی (گران بودن هزینه‌های تامین منابع مالی)', 'detailed_description': 'تضعیف سرمایه انسانی و افزایش هزینه جایگزینی نیرو.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'خروج نیروهای کلیدی'},
    {'category': 'economic', 'text': 'تغییرات نرخ ارز و تورم', 'detailed_description': 'محدودیت در تأمین قطعات، انتقال پول، همکاری با برندهای معتبر خارجی و افزایش هزینه و زمان تأمین که مستقیماً بر قیمت تمام‌شده، تنوع قطعات و رضایت مشتری اثر می‌گذارد.', 'related_standard': '10004 و9001', 'effect_type': 'threat', 'scoring_guide': 'میزان محدودیت در تأمین، نقل‌وانتقال پول و فناوری'},
    {'category': 'economic', 'text': 'قدرت خرید جامعه و رفتار خریداران', 'detailed_description': 'افزایش بهای قطعات، اجرت و خدمات، کاهش قدرت خرید مشتری و سخت‌تر شدن حفظ سودآوری (نمود رفتار خریدار).', 'related_standard': '10004 و9001', 'effect_type': 'threat', 'scoring_guide': 'اثر مستقیم بر قیمت، تقاضا و حاشیه سود'},
    {'category': 'economic', 'text': 'افزایش نرخ اجرت و هزینه قطعات و عدم بازگشت مشتریان به شبکه', 'detailed_description': 'فشار هزینه  ای بر مشتریان موجب ریزش مخاطبان شبکه رسمی،کاهش بهره وری فرایندهای خدمت رسانی و افت شاخص های کیفیت کل و رضایت مشتریان میگردد.', 'related_standard': '10004 و9001', 'effect_type': 'opportunity', 'scoring_guide': 'رشد تقاضای قطعه و تعمیر'},
    {'category': 'social', 'text': 'تغییر الگوی مصرف مشتریان (میل به تعمیرات و یا استفاده از قطعات ارزان)', 'detailed_description': 'کاهش تقاضا برای قطعات اصلی و خدمات رسمی بدلیل فشارهای اقتصادی،ریسک افت کیفیت تعمیرات،افزایش شکایات و افت رضایت مشتریان.', 'related_standard': '10002 و 10004', 'effect_type': 'threat', 'scoring_guide': 'اثر مستقیم بر فروش'},
    {'category': 'social', 'text': 'دسترسی به نیروی انسانی توانمند', 'detailed_description': 'رعایت استانداردهای زیست محیطی در فرایندهای امحا،بازیافت و مدیریت پسماندهای قطعات و مواد شیمیایی حاصل از خدمات تعمیرگاهی.', 'related_standard': '10015', 'effect_type': 'threat', 'scoring_guide': 'شدت فشار مشتری بر قیمت و کیفیت'},
    {'category': 'social', 'text': 'ناآرامی های اجتماعی', 'detailed_description': 'افزایش مرجوعی و هزینه‌های خدماتی، سودآوری فروش را کاهش می‌دهد.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'میزان افزایش مرجوعی'},
    {'category': 'social', 'text': 'بازخوردهای مرتبط با محصول و خدمت در شبکه های مجازی', 'detailed_description': 'خوش‌حسابی می‌تواند شرایط تأمین را بهبود دهد؛ در غیر این صورت قدرت چانه‌زنی شرکت تضعیف می‌شود.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'اثر نظم پرداختی بر شرایط تأمین'},
    {'category': 'social', 'text': 'کاهش انگیزه جوانان برای اشتغال در صنعت خودروسازی', 'detailed_description': 'وفاداری پایین مشتری باعث ریزش سریع بازار در برابر پیشنهاد جذاب‌تر می‌شود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'نرخ جابه‌جایی مشتری'},
    {'category': 'social', 'text': 'افزایش آگاهی اجتماعی نسبت به کیفیت قطعات و خدمات', 'detailed_description': 'ورود قطعات بی‌نام و رقابت ناسالم، بازار رسمی را تضعیف می‌کند.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'شدت اخلال بازار'},
    {'category': 'social', 'text': 'تغییر هرم سنی جمعیت مشتریان', 'detailed_description': 'برتری قیمتی و زمانی رقبا باعث از دست رفتن فروش می‌شود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'شکاف قیمت/زمان'},
    {'category': 'social', 'text': 'ایجاد کمپین های نه به خرید خدمات و محصول از شرکتهای خودروسازی در صورت اعتصابات کارگری', 'detailed_description': 'جذابیت خرید برای مشتری و فشار رقابتی بر شبکه رسمی.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'توان تأمین مالی رقبا'},
    {'category': 'social', 'text': 'اعتماد به برند', 'detailed_description': 'نیاز به یابی شایستگی،اموزش تخصصی مستمر و ارتقای مهارتهای نیروی انسانی کارشناسان و تعمیرکاران جهت ارائه خدمات با کیفیت', 'related_standard': '10015', 'effect_type': 'threat', 'scoring_guide': 'هزینه‌های الزامی'},
    {'category': 'technological', 'text': 'دیجیتالی شدن کسب و کارها', 'detailed_description': 'افزایش شفافیت، کنترل اصالت و بهبود تجربه مشتری در صورت پیاده‌سازی موفق.', 'related_standard': '', 'effect_type': 'opportunity', 'scoring_guide': 'افزایش بهره‌وری و شفافیت'},
    {'category': 'technological', 'text': 'بکارگیری هوش مصنوعی در کسب و کارها', 'detailed_description': 'در شرایط تورمی، تمایز قطعه اصلی و غیر اصلی برای مشتری کم‌رنگ شده و تصمیم خرید صرفاً قیمتی می‌شود؛ نتیجه آن افت فروش قطعه اصلی و تضعیف برند است.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'میزان جایگزینی قطعه اصلی'},
    {'category': 'technological', 'text': 'ورود خودروهای برقی و هیبرید', 'detailed_description': 'لزوم مدیریت مخاطرات زیست محیطی ناشی از باتری های اسقاطی و قطعات الکترونیک،و انطباق فرایندهای تعمیرگاهی با الزامات استاندارد مدیریت محیط زیست.', 'related_standard': '14001', 'effect_type': 'threat', 'scoring_guide': 'احتمال دور زدن شبکه رسمی'},
    {'category': 'technological', 'text': 'تکنولوژی‌های نوین خدمات/قطعات خودرو (مثل rfid و کانکتد کار)', 'detailed_description': 'بکارگیری فناوریهای هوشمند جهت بهینه سازی مصرف انرژی،کاهش پسماند و کنترل پیامدهای زیست محیطی در ارائه خدمات ردیابی و عیب یابی خودرو.', 'related_standard': '14001', 'effect_type': 'threat', 'scoring_guide': 'تمرکز بازار تأمین'},
    {'category': 'technological', 'text': 'تغییر در فناوری تولید قطعات و تعمیرات آنها', 'detailed_description': 'تغییر در ماهیت الاینده ها و مواد مصرفی تعمیرگاهی،که نیازمند بروز رسانی دستورالعمل های زیست محیطی و مدیریت پسماند های حاصل از فناوری های جدید است.', 'related_standard': '14001', 'effect_type': 'both', 'scoring_guide': 'هم‌پوشانی با خدمات شرکت'},
    {'category': 'environmental', 'text': 'افزایش سن ناوگان خودروهای', 'detailed_description': 'نیاز به آموزش، تجهیزات جدید و سرمایه‌گذاری برای حفظ رقابت‌پذیری شبکه خدمات.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'نیاز سرمایه‌گذاری و آموزش'},
    {'category': 'environmental', 'text': 'ناترازی منابع انرژی', 'detailed_description': 'نبود تضمین معتبر، ریسک خرید را به مشتری منتقل کرده و اعتماد به شبکه رسمی و تکرار خرید را کاهش می‌دهد.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'اثر بر اعتماد و وفاداری'},
    {'category': 'environmental', 'text': 'سیاستهای سخت گیرانه استانداردهای آلایندگی', 'detailed_description': 'خروج تقاضا از شبکه رسمی و افزایش رقابت غیرشفاف.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'سهم بازار غیررسمی'},
    {'category': 'environmental', 'text': 'الزام به استفاده از انرژیهای تجدیدپذیر (مثل سلولهای خورشیدی)', 'detailed_description': 'اثر تجمیعی جایگزین‌ها منجر به افت سود و افزایش هزینه سربار می‌شود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'شدت افت سودآوری'},
    {'category': 'environmental', 'text': 'مدیریت پسماند و بازیافت', 'detailed_description': 'تقویت روابط زنجیره تأمین رقبا و قفل شدن تأمین‌کننده.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'عمق همکاری رقبا'},
    {'category': 'environmental', 'text': 'تامین براساس الزامات کنشی و واکنشی مدیریت پسماند', 'detailed_description': 'تقویت مسئولیت پذیری اجتماعی و محیط زیستی سازمان که منجر به ارتقای تصویر ذهنی برند،جلب اعتماد ذینفعان و انطباق با الزامات زیست محیطی میشود.', 'related_standard': '14001', 'effect_type': 'both', 'scoring_guide': 'رعایت الزامات زیست محیطی'},
    {'category': 'legal', 'text': 'قوانین، استانداردها و تنظیم گری', 'detailed_description': 'الزام به توسعه پلتفرم‌های فروش، CRM و زنجیره تأمین دیجیتال.', 'related_standard': '', 'effect_type': 'opportunity', 'scoring_guide': 'اثر بر رقابت‌پذیری شبکه'},
    {'category': 'legal', 'text': 'افزایش زیاد دستمزد سالانه', 'detailed_description': 'کاهش انعطاف‌پذیری قیمت‌گذاری و فشار بر سود.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'کاهش انعطاف قیمت‌گذاری'},
    {'category': 'legal', 'text': 'الزام کد رهگیری و شناسه کالا بر قطعات', 'detailed_description': 'شفافیت قیمت، مقایسه‌پذیری و تحویل سریع، قدرت چانه‌زنی خریدار را به‌شدت افزایش داده و نقش شبکه سنتی را تضعیف می‌کند.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'تسلط مشتری بر اطلاعات بازار'},
    {'category': 'legal', 'text': 'قوانین جدید مربوط به سامانه مودیان مالیاتی', 'detailed_description': 'فشار مستقیم بر نقدینگی و محدود شدن توسعه عملیات.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'اثر بر جریان نقدی'},
    {'category': 'legal', 'text': 'استاندارد 122 گانه خودرو', 'detailed_description': 'تغییر ماهیت تقاضا برای قطعات و خدمات؛ تهدید در کوتاه‌مدت و فرصت در صورت آمادگی.', 'related_standard': '', 'effect_type': 'both', 'scoring_guide': 'آمادگی برای تغییر فناوری'},
    {'category': 'legal', 'text': 'تشدید نظارت بر استانداردهای مدیریت کیفیت قطعات و خدمات(ISQI )', 'detailed_description': 'افت فروش قطعه اصلی و کاهش سودآوری شبکه رسمی.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'شدت جایگزینی'},
    {'category': 'legal', 'text': 'استانداردهای مدیریتی شامل 9000،10002،10004،10015،14001', 'detailed_description': 'لزوم پیاده سازی،یکپارچه سازی و حفظ انطباق فرایندهای سازمان با الزامات استانداردهای مدیریتی شامل: مدیریت کیفیت (ISO9001) رسیدگی به شکایات مشتریان (ISO10002) پایش و سنجش رضایت مشتریان (ISO10004) ارتقای شایستگی و اموزش نیروی انسانی (ISO10015) مدیریت زیست محیطی (ISO14001) جهت ارتقای کارایی عملیاتی،افزایش رضایت ذینفعان و تحقق بهبود مستمر در سطح شبکه خدمات.', 'related_standard': '9000،10002،10004،10015،14001', 'effect_type': 'threat', 'scoring_guide': 'یکپارچه سازی استانداردها'},
    {'category': 'legal', 'text': 'مقررات مربوط به ایمنی و بهداشت کار/ بیمه', 'detailed_description': 'امکان مانور قیمتی، تبلیغاتی و سرمایه‌گذاری بیشتر.', 'related_standard': '', 'effect_type': 'threat', 'scoring_guide': 'فاصله توان مالی'},
]


class Command(BaseCommand):
    help = "بانک عوامل PESTEL سایپا یدک را با نسخه‌ی نهایی (۳۸ ردیف واقعی) پاک و جایگزین می‌کند."

    def handle(self, *args, **options):
        PestelFactor.objects.all().delete()
        for order, row in enumerate(ROWS):
            PestelFactor.objects.create(kind='factor', order=order, **row)
        self.stdout.write(self.style.SUCCESS(f"ثبت شد: {len(ROWS)} عامل PESTEL."))
