from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "strategic"

urlpatterns = [
    path("", views.home, name="home"),
    path("documents/", views.documents, name="documents"),
    path("documents/download/<int:pk>/", views.document_download, name="document_download"),
    path("documents/delete/<int:pk>/", views.document_delete, name="document_delete"),
    path("identity/", views.org_identity, name="org_identity"),
    path("identity/value/delete/<int:pk>/", views.org_value_delete, name="org_value_delete"),
    path("identity/policy/delete/<int:pk>/", views.policy_point_delete, name="policy_point_delete"),

    path("research/", views.research, name="research"),
    path("research/delete/<int:pk>/", views.study_delete, name="study_delete"),
    path("legal-requirements/", views.legal_requirements, name="legal_requirements"),
    path("legal-requirements/delete/<int:pk>/", views.legal_requirement_delete, name="legal_requirement_delete"),
    path("legal-requirements/export/", views.legal_requirement_export, name="legal_requirement_export"),
    path("legal-requirements/import/", views.legal_requirement_import, name="legal_requirement_import"),
    path("stakeholders/", views.stakeholders, name="stakeholders"),
    path("stakeholders/delete/<int:pk>/", views.stakeholder_delete, name="stakeholder_delete"),
    path("stakeholders/export/", views.stakeholder_export, name="stakeholder_export"),
    path("stakeholders/import/", views.stakeholder_import, name="stakeholder_import"),

    path("roadmap/", views.roadmap, name="roadmap"),
    path("roadmap/delete/<int:pk>/", views.initiative_delete, name="initiative_delete"),
    path("roadmap/export/", views.initiative_export, name="initiative_export"),
    path("roadmap/export-relationships/", views.initiative_relationships_export, name="initiative_relationships_export"),
    path("roadmap/import/", views.initiative_import, name="initiative_import"),
    path("roadmap/bsc-sync/", views.bsc_sync, name="bsc_sync"),

    path("market-intel/", views.market_intel, name="market_intel"),
    path("market-intel/export/", views.market_intel_export, name="market_intel_export"),
    path("market-intel/import/", views.market_intel_import, name="market_intel_import"),
    path("market-intel/delete/<str:model_key>/<int:pk>/", views.market_intel_delete, name="market_intel_delete"),
    path("users/", views.user_list, name="user_list"),
    path("users/add/", views.user_edit, name="user_add"),
    path("users/<int:pk>/edit/", views.user_edit, name="user_edit"),
    path("users/<int:pk>/toggle/", views.user_toggle_active, name="user_toggle_active"),
    path("market/", views.market, name="market"),
    path("market/delete/<int:pk>/", views.competitor_delete, name="competitor_delete"),

    path("environmental-factors/", views.environmental_factors, name="environmental_factors"),
    path("raw-factors-archive/", views.raw_factors_archive, name="raw_factors_archive"),
    path("raw-factors-archive/delete/<int:pk>/", views.raw_factor_delete, name="raw_factor_delete"),
    path("raw-factors-archive/export/", views.raw_factors_export, name="raw_factors_export"),
    path("raw-factors-archive/import/", views.raw_factors_import, name="raw_factors_import"),
    path("environmental-factors/delete/<int:pk>/", views.environmental_factor_delete, name="environmental_factor_delete"),
    path("environmental-factors/export/", views.environmental_factor_export, name="environmental_factor_export"),
    path("environmental-factors/import/", views.environmental_factor_import, name="environmental_factor_import"),
    path("pestel/", views.pestel, name="pestel"),
    path("pestel/delete/<int:pk>/", views.pestel_delete, name="pestel_delete"),
    path("cross-impact/", views.cross_impact, name="cross_impact"),
    path("cross-impact/delete/<int:pk>/", views.cross_impact_delete, name="cross_impact_delete"),
    path("cross-impact/matrix/", views.cross_impact_matrix, name="cross_impact_matrix"),
    path("cross-impact/matrix/export/", views.cross_impact_matrix_export, name="cross_impact_matrix_export"),
    path("cross-impact/matrix/import/", views.cross_impact_matrix_import, name="cross_impact_matrix_import"),
    path("scenarios/", views.scenarios, name="scenarios"),
    path("scenarios/response-strategy/delete/<int:pk>/", views.scenario_response_strategy_delete, name="scenario_response_strategy_delete"),
    path("company-goals/", views.company_goals, name="company_goals"),
    path("company-goals/objective/delete/<int:pk>/", views.company_objective_delete, name="company_objective_delete"),
    path("company-goals/kpi/delete/<int:pk>/", views.company_kpi_delete, name="company_kpi_delete"),
    path("company-goals/kpi/export/", views.company_kpi_export, name="company_kpi_export"),
    path("company-goals/kpi/import/", views.company_kpi_import, name="company_kpi_import"),
    path("company-goals/kpi/refresh/", views.company_kpi_refresh_from_source, name="company_kpi_refresh_from_source"),
    path("operational-kpis/", views.operational_kpis, name="operational_kpis"),
    path("operational-kpis/delete/<int:pk>/", views.operational_kpi_delete, name="operational_kpi_delete"),
    path("operational-kpis/export/", views.operational_kpi_export, name="operational_kpi_export"),
    path("operational-kpis/import/", views.operational_kpi_import, name="operational_kpi_import"),
    path("porter/", views.porter, name="porter"),
    path("porter/delete/<int:pk>/", views.porter_delete, name="porter_delete"),
    path("mckinsey7s/", views.mckinsey7s, name="mckinsey7s"),
    path("value-chain/", views.value_chain, name="value_chain"),
    path("stratmap/", views.stratmap, name="stratmap"),
    path("stratmap/print/", views.stratmap_print, name="stratmap_print"),
    path("stratmap/print-full/", views.stratmap_print_full, name="stratmap_print_full"),
    path("stratmap/export-excel/", views.stratmap_export_excel, name="stratmap_export_excel"),
    path("stratmap/delete/<int:pk>/", views.objective_delete, name="objective_delete"),
    path("stratmap/theme/add/", views.theme_add, name="theme_add"),
    path("stratmap/theme/delete/<int:pk>/", views.theme_delete, name="theme_delete"),
    path("stratmap/kpi/save/", views.strategic_kpi_save, name="strategic_kpi_save"),
    path("stratmap/kpi/delete/<int:pk>/", views.strategic_kpi_delete, name="strategic_kpi_delete"),
    path("business-unit/add/", views.business_unit_add, name="business_unit_add"),

    path("swot/", views.swot, name="swot"),
    path("swot/print/", views.swot_print, name="swot_print"),
    path("swot/delete/<int:pk>/", views.swot_delete, name="swot_delete"),
    path("swot/tows/delete/<int:pk>/", views.tows_delete, name="tows_delete"),

    path("risk/", views.risk, name="risk"),
    path("risk/delete/<int:pk>/", views.risk_delete, name="risk_delete"),

    path("login/", auth_views.LoginView.as_view(template_name="strategic/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="strategic:login"), name="logout"),
]
