# Generated by Django 5.2.15 on 2026-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مطالعه')),
                ('field', models.CharField(blank=True, default='عمومی', max_length=100, verbose_name='حوزه')),
                ('date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ (شمسی)')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('progress', 'در حال انجام'), ('done', 'تکمیل\u200cشده')], default='planned', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مطالعه',
                'verbose_name_plural': 'مطالعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
