# Generated by Django 5.2.15 on 2026-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان ابتکار')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='واحد مسئول')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت (٪)')),
                ('status', models.CharField(choices=[('in_progress', 'در حال اجرا'), ('on_track', 'در مسیر'), ('needs_attention', 'نیازمند پیگیری'), ('digital', 'ابتکار دیجیتال'), ('done', 'تکمیل\u200cشده')], default='on_track', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ابتکار',
                'verbose_name_plural': 'ابتکارات',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان ریسک')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='مسئول')),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, 'کم'), (2, 'متوسط'), (3, 'زیاد'), (4, 'خیلی زیاد')], default=2, verbose_name='احتمال وقوع')),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, 'کم'), (2, 'متوسط'), (3, 'زیاد'), (4, 'خیلی زیاد')], default=2, verbose_name='شدت اثر')),
                ('mitigation', models.TextField(blank=True, verbose_name='اقدام کاهشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ریسک',
                'verbose_name_plural': 'ریسک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SWOTItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('s', 'نقطه قوت'), ('w', 'نقطه ضعف'), ('o', 'فرصت'), ('t', 'تهدید')], max_length=1)),
                ('text', models.CharField(max_length=300, verbose_name='متن')),
                ('impact', models.CharField(choices=[('high', 'بالا'), ('med', 'متوسط')], default='med', max_length=10, verbose_name='اهمیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد SWOT',
                'verbose_name_plural': 'موارد SWOT',
                'ordering': ['created_at'],
            },
        ),
    ]
