# Generated by Django 5.2.15 on 2026-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0002_initiative_risk_swotitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='کد (مثل F1، C2)')),
                ('perspective', models.CharField(choices=[('financial', 'مالی'), ('customer', 'مشتری'), ('process', 'فرآیندهای داخلی'), ('learning', 'یادگیری و رشد')], max_length=20, verbose_name='منظر BSC')),
                ('theme', models.CharField(choices=[('operational', 'تعالی عملیاتی و کیفیت'), ('growth', 'رشد بازار و سودآوری'), ('digital', 'نوآوری و تحول دیجیتال')], max_length=20, verbose_name='محور استراتژیک')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان هدف')),
                ('kpi', models.CharField(blank=True, max_length=300, verbose_name='KPI')),
                ('status', models.CharField(choices=[('on', 'در مسیر هدف'), ('watch', 'نیازمند پیگیری'), ('risk', 'در معرض ریسک')], default='on', max_length=10, verbose_name='وضعیت')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'هدف استراتژیک',
                'verbose_name_plural': 'اهداف استراتژیک (نقشه استراتژیک)',
                'ordering': ['order', 'code'],
            },
        ),
    ]
