# Generated by Django 5.2.15 on 2026-07-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0003_strategicobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام بازیگر')),
                ('market_share', models.PositiveSmallIntegerField(default=0, verbose_name='سهم بازار (٪)')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط قوت (هر خط یک مورد)')),
                ('weaknesses', models.TextField(blank=True, verbose_name='نقاط ضعف (هر خط یک مورد)')),
                ('recent_move', models.CharField(blank=True, max_length=300, verbose_name='آخرین حرکت')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'بازیگر بازار',
                'verbose_name_plural': 'هوش رقابتی و بازار',
                'ordering': ['order', '-market_share'],
            },
        ),
        migrations.CreateModel(
            name='PestelFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('political', 'سیاسی'), ('economic', 'اقتصادی'), ('social', 'اجتماعی'), ('technological', 'فناورانه'), ('environmental', 'زیست\u200cمحیطی'), ('legal', 'قانونی')], max_length=20, verbose_name='بُعد')),
                ('text', models.CharField(max_length=300, verbose_name='عامل محیطی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'عامل PESTEL',
                'verbose_name_plural': 'تحلیل PESTEL',
                'ordering': ['category', 'order'],
            },
        ),
    ]
