# Generated by Django 5.2.15 on 2026-07-03 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0004_competitor_pestelfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
