# Generated by Django 5.2.15 on 2026-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0005_competitor_created_at_pestelfactor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='feeds_into',
            field=models.ManyToManyField(blank=True, related_name='fed_by', to='strategic.strategicobjective', verbose_name='این هدف به کدام هدف(ها) کمک می\u200cکند'),
        ),
    ]
