# Generated by Django 5.2.15 on 2026-07-03 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0006_strategicobjective_feeds_into'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOWSStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('so', 'SO — تهاجمی'), ('st', 'ST — تنوع'), ('wo', 'WO — بازنگری'), ('wt', 'WT — تدافعی')], max_length=2, verbose_name='نوع راهبرد')),
                ('text', models.CharField(max_length=300, verbose_name='متن راهبرد')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'راهبرد TOWS',
                'verbose_name_plural': 'راهبردهای TOWS',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='swotitem',
            options={'ordering': ['-weight', 'created_at'], 'verbose_name': 'مورد SWOT', 'verbose_name_plural': 'موارد SWOT'},
        ),
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.CharField(choices=[('ops', 'عملیات'), ('mkt', 'بازار'), ('fin', 'مالی'), ('legal', 'حقوقی/مقرراتی'), ('it', 'فناوری اطلاعات'), ('hr', 'منابع انسانی')], default='ops', max_length=10, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='risk',
            name='kri',
            field=models.CharField(blank=True, max_length=200, verbose_name='شاخص کلیدی ریسک (KRI)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='linked_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='strategic.strategicobjective', verbose_name='هدف استراتژیک مرتبط'),
        ),
        migrations.AddField(
            model_name='risk',
            name='response_strategy',
            field=models.CharField(choices=[('mitigate', 'کاهش (Mitigate)'), ('transfer', 'انتقال (Transfer)'), ('accept', 'پذیرش (Accept)'), ('avoid', 'اجتناب (Avoid)')], default='mitigate', max_length=10, verbose_name='راهبرد پاسخ'),
        ),
        migrations.AddField(
            model_name='risk',
            name='trend',
            field=models.CharField(choices=[('up', 'افزایشی'), ('down', 'کاهشی'), ('flat', 'پایدار')], default='flat', max_length=5, verbose_name='روند نسبت به دوره قبل'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='weight',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵')], default=3, verbose_name='وزن اهمیت (۱ تا ۵)'),
        ),
    ]
