# Generated by Django 5.2.15 on 2026-07-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0007_towsstrategy_alter_swotitem_options_risk_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='inherent_impact',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ - بسیار کم'), (2, '۲ - کم'), (3, '۳ - متوسط'), (4, '۴ - زیاد'), (5, '۵ - بسیار زیاد')], default=4, verbose_name='شدت اثر (ذاتی)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='inherent_likelihood',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ - بسیار کم'), (2, '۲ - کم'), (3, '۳ - متوسط'), (4, '۴ - زیاد'), (5, '۵ - بسیار زیاد')], default=4, verbose_name='احتمال (ذاتی)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='target_impact',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ - بسیار کم'), (2, '۲ - کم'), (3, '۳ - متوسط'), (4, '۴ - زیاد'), (5, '۵ - بسیار زیاد')], default=2, verbose_name='شدت اثر (هدف)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='target_likelihood',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ - بسیار کم'), (2, '۲ - کم'), (3, '۳ - متوسط'), (4, '۴ - زیاد'), (5, '۵ - بسیار زیاد')], default=2, verbose_name='احتمال (هدف)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='category',
            field=models.CharField(choices=[('ops', 'زنجیره تأمین/عملیاتی'), ('mkt', 'بازار و رقابت'), ('fin', 'مالی و ارزی'), ('legal', 'انطباق و قانونی'), ('it', 'فناوری اطلاعات'), ('hr', 'منابع انسانی')], default='ops', max_length=10, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ - بسیار کم'), (2, '۲ - کم'), (3, '۳ - متوسط'), (4, '۴ - زیاد'), (5, '۵ - بسیار زیاد')], default=3, verbose_name='شدت اثر (باقیمانده)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ - بسیار کم'), (2, '۲ - کم'), (3, '۳ - متوسط'), (4, '۴ - زیاد'), (5, '۵ - بسیار زیاد')], default=3, verbose_name='احتمال (باقیمانده)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='linked_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='strategic.strategicobjective', verbose_name='هدف استراتژیک تهدیدشده'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigation',
            field=models.TextField(blank=True, verbose_name='اقدامات کنترلی (هر خط یک مورد)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.CharField(blank=True, max_length=150, verbose_name='مالک ریسک'),
        ),
    ]
