# Generated by Django 5.2.15 on 2026-07-04 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0008_risk_inherent_impact_risk_inherent_likelihood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام کسب\u200cوکار')),
                ('archetype', models.CharField(choices=[('intimacy', 'صمیمیت با مشتری'), ('excellence', 'برتری عملیاتی'), ('exclusive', 'ایجاد فضای انحصاری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='رویکرد استراتژیک')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='strategic.businessunit', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.businessunit', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='towsstrategy',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tows_strategies', to='strategic.businessunit', verbose_name='کسب\u200cوکار'),
        ),
    ]
