# Generated by Django 5.2.15 on 2026-07-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0009_businessunit_strategicobjective_business_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محور')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='strategic.businessunit', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'محور نقشه استراتژیک',
                'verbose_name_plural': 'محورهای نقشه استراتژیک',
                'ordering': ['business_unit', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='strategic.strategytheme', verbose_name='محور استراتژیک'),
        ),
    ]
