# Generated by Django 5.2.15 on 2026-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0010_strategytheme_alter_strategicobjective_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestelfactor',
            name='kind',
            field=models.CharField(choices=[('factor', 'عامل محیطی'), ('opportunity', 'فرصت'), ('threat', 'تهدید')], default='factor', max_length=15, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='pestelfactor',
            name='text',
            field=models.CharField(max_length=500, verbose_name='متن'),
        ),
    ]
