# Generated by Django 5.2.15 on 2026-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0011_pestelfactor_kind_alter_pestelfactor_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorterForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.CharField(choices=[('rivalry', 'شدت رقابت موجود'), ('buyer_power', 'قدرت چانه\u200cزنی مشتریان'), ('supplier_power', 'قدرت چانه\u200cزنی تأمین\u200cکنندگان'), ('new_entrants', 'تهدید ورود رقبای جدید'), ('substitutes', 'تهدید کالاها/خدمات جایگزین')], max_length=20, unique=True, verbose_name='نیرو')),
                ('level', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('very_high', 'بسیار زیاد')], default='medium', max_length=10, verbose_name='شدت')),
                ('reasons', models.TextField(blank=True, verbose_name='دلایل (هر خط یک مورد)')),
                ('conclusion', models.TextField(blank=True, verbose_name='نتیجه')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نیروی پورتر',
                'verbose_name_plural': 'تحلیل پنج نیروی پورتر',
                'ordering': ['force'],
            },
        ),
    ]
