# Generated by Django 5.2.15 on 2026-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0012_porterforce'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(blank=True, verbose_name='چشم\u200cانداز')),
                ('mission', models.TextField(blank=True, verbose_name='مأموریت')),
                ('signed_by', models.CharField(blank=True, max_length=150, verbose_name='امضاکننده')),
                ('signed_role', models.CharField(blank=True, max_length=150, verbose_name='سمت امضاکننده')),
                ('signed_date', models.CharField(blank=True, max_length=50, verbose_name='تاریخ امضا (شمسی، متن آزاد)')),
            ],
            options={
                'verbose_name': 'چشم\u200cانداز و مأموریت',
                'verbose_name_plural': 'چشم\u200cانداز و مأموریت',
            },
        ),
        migrations.CreateModel(
            name='OrgValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='ارزش سازمانی')),
                ('is_center', models.BooleanField(default=False, verbose_name='آیا مرکز چرخ است؟')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ارزش سازمانی',
                'verbose_name_plural': 'ارزش\u200cهای سازمانی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QualityPolicyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره بند')),
                ('text', models.TextField(verbose_name='متن بند')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'بند خط\u200cمشی کیفیت',
                'verbose_name_plural': 'بندهای خط\u200cمشی کیفیت',
                'ordering': ['order'],
            },
        ),
    ]
