# Generated by Django 5.2.15 on 2026-07-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0013_orgidentity_orgvalue_qualitypolicypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='strategic.businessunit', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='strategic.strategicobjective', verbose_name='اهداف استراتژیک مرتبط'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان پروژه'),
        ),
    ]
