# Generated by Django 5.2.15 on 2026-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0014_initiative_business_unit_initiative_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='cause',
            field=models.TextField(blank=True, verbose_name='منشأ/علت بروز ریسک'),
        ),
        migrations.AddField(
            model_name='risk',
            name='consequence',
            field=models.TextField(blank=True, verbose_name='پیامد ریسک'),
        ),
    ]
