# Generated by Django 5.2.15 on 2026-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0015_risk_cause_risk_consequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='McKinsey7S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('strategy', 'استراتژی'), ('structure', 'ساختار'), ('systems', 'سیستم\u200cها'), ('shared_values', 'ارزش\u200cهای مشترک'), ('skills', 'مهارت\u200cها'), ('staff', 'کارکنان'), ('style', 'سبک')], max_length=20, unique=True, verbose_name='مؤلفه')),
                ('status', models.TextField(blank=True, verbose_name='وضعیت فعلی')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط قوت (هر خط یک مورد)')),
                ('weaknesses', models.TextField(blank=True, verbose_name='نقاط ضعف/ریسک\u200cها (هر خط یک مورد)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مؤلفه McKinsey 7S',
                'verbose_name_plural': 'تحلیل McKinsey 7S',
            },
        ),
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.CharField(blank=True, max_length=150, verbose_name='مسئول ریسک/پروژه'),
        ),
    ]
