# Generated by Django 5.2.15 on 2026-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0016_mckinsey7s_alter_risk_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueChainActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('infra', 'زیرساخت\u200cهای شرکت'), ('hr', 'مدیریت منابع انسانی'), ('tech', 'توسعه فناوری'), ('procurement', 'تدارکات'), ('inbound', 'لجستیک ورودی'), ('operations', 'عملیات'), ('outbound', 'لجستیک خروجی'), ('marketing', 'بازاریابی و فروش'), ('service', 'خدمات به مشتری')], max_length=20, unique=True, verbose_name='فعالیت')),
                ('content', models.TextField(blank=True, verbose_name='اقدامات/محتوا (هر خط یک مورد)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فعالیت زنجیره ارزش پورتر',
                'verbose_name_plural': 'زنجیره ارزش پورتر',
            },
        ),
    ]
