# Generated by Django 5.2.15 on 2026-07-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0017_valuechainactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotitem',
            name='source_7s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.mckinsey7s', verbose_name='مؤلفه McKinsey 7S مرتبط'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='source_pestel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.pestelfactor', verbose_name='عامل محیطی مرتبط (PESTEL)'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='source_porter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.porterforce', verbose_name='نیروی پورتر مرتبط'),
        ),
        migrations.AddField(
            model_name='swotitem',
            name='source_value_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.valuechainactivity', verbose_name='فعالیت زنجیره ارزش مرتبط'),
        ),
    ]
