# Generated by Django 5.2.15 on 2026-07-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0018_swotitem_source_7s_swotitem_source_pestel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towsstrategy',
            name='source_items',
            field=models.ManyToManyField(blank=True, related_name='tows_strategies', to='strategic.swotitem', verbose_name='موارد SWOT مبنا'),
        ),
    ]
