# Generated by Django 5.2.15 on 2026-07-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0019_towsstrategy_source_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='source_tows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='strategic.towsstrategy', verbose_name='راهبرد TOWS مبنا'),
        ),
    ]
