# Generated by Django 5.2.15 on 2026-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0020_strategicobjective_source_tows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='واحد/مدیریت ثبت\u200cکننده')),
                ('name', models.CharField(max_length=200, verbose_name='نام ذی\u200cنفع')),
                ('channel', models.CharField(blank=True, max_length=300, verbose_name='کانال ارتباطی')),
                ('need', models.TextField(blank=True, verbose_name='نیاز/انتظار ذی\u200cنفع')),
                ('risk_text', models.TextField(blank=True, verbose_name='ریسک')),
                ('risk_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد ریسک')),
                ('opportunity_text', models.TextField(blank=True, verbose_name='فرصت')),
                ('opportunity_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد فرصت')),
                ('action', models.TextField(blank=True, verbose_name='اقدام تعریف\u200cشده')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('done', 'رسیدگی\u200cشده')], default='open', max_length=15, verbose_name='وضعیت رسیدگی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ذی\u200cنفع',
                'verbose_name_plural': 'مخزن ذی\u200cنفعان',
                'ordering': ['-risk_score'],
            },
        ),
    ]
