# Generated by Django 5.2.15 on 2026-07-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0021_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotitem',
            name='source_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.stakeholder', verbose_name='ذی\u200cنفع مرتبط'),
        ),
    ]
