# Generated by Django 5.2.15 on 2026-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0022_swotitem_source_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestelfactor',
            name='horizon',
            field=models.CharField(choices=[('short', 'کوتاه\u200cمدت'), ('medium', 'میان\u200cمدت'), ('long', 'بلندمدت')], default='medium', max_length=10, verbose_name='افق زمانی'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='impact_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='میزان اثر'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='probability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='احتمال وقوع'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='trend',
            field=models.CharField(choices=[('up', 'صعودی'), ('down', 'نزولی'), ('flat', 'ثابت')], default='flat', max_length=10, verbose_name='روند تغییر'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='uncertainty',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='میزان عدم\u200cقطعیت'),
        ),
    ]
