# Generated by Django 5.2.15 on 2026-07-30 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0023_pestelfactor_horizon_pestelfactor_impact_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossImpactFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='عامل')),
                ('quadrant', models.CharField(choices=[('driver', 'پیشران\u200cهای کلیدی'), ('relay', 'متغیرهای دووجهی'), ('watch', 'دیده\u200cبانی'), ('resultant', 'متغیرهای نتیجه')], max_length=12, verbose_name='ناحیه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('linked_pestel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_impact_factors', to='strategic.pestelfactor', verbose_name='عامل PESTEL مرتبط (اختیاری)')),
            ],
            options={
                'verbose_name': 'عامل اثرات متقابل',
                'verbose_name_plural': 'تحلیل اثرات متقابل',
                'ordering': ['quadrant', 'order'],
            },
        ),
    ]
