# Generated by Django 5.2.15 on 2026-07-30 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0024_crossimpactfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossImpactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(0, 'بدون اثر'), (1, 'کم'), (2, 'متوسط'), (3, 'زیاد')], default=0, verbose_name='میزان اثر')),
                ('from_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='strategic.crossimpactfactor')),
                ('to_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='strategic.crossimpactfactor')),
            ],
            options={
                'verbose_name': 'اثر مستقیم',
                'verbose_name_plural': 'ماتریس اثرات مستقیم',
                'unique_together': {('from_factor', 'to_factor')},
            },
        ),
    ]
