# Generated by Django 5.2.15 on 2026-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0025_crossimpactlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadrant', models.CharField(choices=[('prosperity', 'پیش به سوی بالندگی'), ('exploration', 'کنکاش محیطی'), ('rocky', 'گذر از سنگلاخ'), ('foggy', 'هوای مه\u200cآلود')], max_length=15, unique=True, verbose_name='ناحیه')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان سناریو')),
                ('narrative', models.TextField(blank=True, verbose_name='روایت کامل سناریو')),
                ('is_selected', models.BooleanField(default=False, verbose_name='سناریوی منتخب/مبنا')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سناریو',
                'verbose_name_plural': 'سناریوهای راهبردی',
                'ordering': ['quadrant'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioAxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis1_name', models.CharField(default='امکان تأمین منابع مالی', max_length=200, verbose_name='عنوان محور عمودی')),
                ('axis1_positive', models.CharField(default='دستیابی به منابع مالی', max_length=150, verbose_name='قطب مثبت محور عمودی')),
                ('axis1_negative', models.CharField(default='عدم دستیابی به منابع مالی', max_length=150, verbose_name='قطب منفی محور عمودی')),
                ('axis2_name', models.CharField(default='وضعیت بین\u200cالمللی', max_length=200, verbose_name='عنوان محور افقی')),
                ('axis2_positive', models.CharField(default='تعاملات هدفمند بین\u200cالمللی', max_length=150, verbose_name='قطب مثبت محور افقی')),
                ('axis2_negative', models.CharField(default='تشدید محدودیت\u200cهای بین\u200cالمللی', max_length=150, verbose_name='قطب منفی محور افقی')),
            ],
            options={
                'verbose_name': 'محورهای سناریو',
                'verbose_name_plural': 'محورهای سناریو',
            },
        ),
    ]
