# Generated by Django 5.2.15 on 2026-07-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0026_scenario_scenarioaxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['-risk_score'], 'verbose_name': 'ذینفع', 'verbose_name_plural': 'مخزن ذینفعان'},
        ),
        migrations.AddField(
            model_name='swotitem',
            name='source_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.scenario', verbose_name='سناریوی مرتبط'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام ذینفع'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='need',
            field=models.TextField(blank=True, verbose_name='نیاز/انتظار ذینفع'),
        ),
        migrations.AlterField(
            model_name='swotitem',
            name='source_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swot_items', to='strategic.stakeholder', verbose_name='ذینفع مرتبط'),
        ),
    ]
