# Generated by Django 5.2.15 on 2026-07-30 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0027_alter_stakeholder_options_swotitem_source_scenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد هدف')),
                ('group_title', models.CharField(blank=True, max_length=300, verbose_name='هدف کلان استراتژیک گروه')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان هدف')),
                ('description', models.TextField(blank=True, verbose_name='تشریح هدف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'هدف کلان شرکت',
                'verbose_name_plural': 'اهداف کلان شرکت',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد شاخص')),
                ('domain', models.CharField(choices=[('Q', 'کیفیت (Quality)'), ('D', 'تحویل/حجم (Delivery)'), ('C', 'هزینه/درآمد (Cost)'), ('M', 'مدیریتی (Management)')], default='Q', max_length=1, verbose_name='حوزه اثربخشی')),
                ('name', models.CharField(max_length=300, verbose_name='شاخص کلیدی')),
                ('unit', models.CharField(blank=True, max_length=60, verbose_name='واحد سنجش')),
                ('target_1404', models.CharField(blank=True, max_length=60, verbose_name='هدف سال ۱۴۰۴')),
                ('actual_1404', models.CharField(blank=True, max_length=60, verbose_name='آخرین وضعیت ۱۴۰۴')),
                ('target_1405', models.CharField(blank=True, max_length=60, verbose_name='هدف سال ۱۴۰۵')),
                ('suggested_target', models.CharField(blank=True, max_length=200, verbose_name='هدف پیشنهادی')),
                ('is_monitoring', models.BooleanField(default=False, verbose_name='صرفاً پایشی (بدون هدف مستقیم)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('objectives', models.ManyToManyField(blank=True, related_name='kpis', to='strategic.companyobjective', verbose_name='اهداف مرتبط')),
            ],
            options={
                'verbose_name': 'شاخص کلان شرکت',
                'verbose_name_plural': 'شاخص\u200cهای کلان شرکت',
                'ordering': ['order'],
            },
        ),
    ]
