# Generated by Django 5.2.15 on 2026-07-30 20:06

import strategic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0028_companyobjective_companykpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان سند')),
                ('category', models.CharField(choices=[('upstream', 'سند بالادستی'), ('guideline', 'دستورالعمل')], default='upstream', max_length=15, verbose_name='دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('file', models.FileField(upload_to=strategic.models.document_upload_path, verbose_name='فایل')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد و دستورالعمل\u200cها',
                'ordering': ['category', 'order', '-uploaded_at'],
            },
        ),
    ]
