# Generated by Django 5.2.15 on 2026-07-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0029_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تصویب'),
        ),
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='کد دستورالعمل/سند'),
        ),
    ]
