# Generated by Django 5.2.15 on 2026-07-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0030_document_approved_at_document_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شاخص')),
                ('unit', models.CharField(blank=True, max_length=60, verbose_name='واحد سنجش')),
                ('target', models.CharField(blank=True, max_length=60, verbose_name='مقدار هدف')),
                ('actual', models.CharField(blank=True, max_length=60, verbose_name='مقدار واقعی')),
                ('trend', models.CharField(choices=[('up', 'صعودی'), ('down', 'نزولی'), ('flat', 'پایدار')], default='flat', max_length=10, verbose_name='روند')),
                ('status', models.CharField(choices=[('on_track', 'در مسیر هدف'), ('at_risk', 'در معرض ریسک'), ('off_track', 'خارج از مسیر')], default='on_track', max_length=10, verbose_name='وضعیت')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='مسئول')),
                ('period', models.CharField(blank=True, max_length=60, verbose_name='دوره پایش')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategic.strategicobjective', verbose_name='هدف مرتبط')),
            ],
            options={
                'verbose_name': 'شاخص هدف استراتژیک',
                'verbose_name_plural': 'شاخص\u200cهای اهداف استراتژیک',
                'ordering': ['order'],
            },
        ),
    ]
