# Generated by Django 5.2.15 on 2026-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0031_strategickpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companykpi',
            name='suggested_target',
        ),
        migrations.AddField(
            model_name='companykpi',
            name='actual_1405',
            field=models.CharField(blank=True, max_length=60, verbose_name='عملکرد ۱۴۰۵'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='linked_company_kpis',
            field=models.ManyToManyField(blank=True, related_name='linked_objectives', to='strategic.companykpi', verbose_name='شاخص\u200cهای استراتژیک مرتبط'),
        ),
        migrations.AlterField(
            model_name='companykpi',
            name='actual_1404',
            field=models.CharField(blank=True, max_length=60, verbose_name='عملکرد ۱۴۰۴'),
        ),
    ]
