# Generated by Django 5.2.15 on 2026-07-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0032_remove_companykpi_suggested_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companykpi',
            name='progress_1405',
            field=models.CharField(blank=True, max_length=20, verbose_name='درصد تحقق (دستی)'),
        ),
    ]
