# Generated by Django 5.2.15 on 2026-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0033_companykpi_progress_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='linked_kpis',
            field=models.ManyToManyField(blank=True, related_name='strategic_objectives', to='strategic.companykpi', verbose_name='شاخص\u200cهای استراتژیک مرتبط'),
        ),
    ]
