# Generated by Django 5.2.15 on 2026-07-31 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0034_strategicobjective_linked_kpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='related_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='strategic.scenario', verbose_name='سناریوی مرتبط'),
        ),
    ]
