# Generated by Django 5.2.15 on 2026-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0035_risk_related_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='related_scenario',
        ),
        migrations.AddField(
            model_name='risk',
            name='related_scenario',
            field=models.ManyToManyField(blank=True, related_name='risks', to='strategic.scenario', verbose_name='سناریوهای مرتبط'),
        ),
    ]
