# Generated by Django 5.2.15 on 2026-08-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0036_remove_risk_related_scenario_risk_related_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossimpactfactor',
            name='quadrant',
            field=models.CharField(choices=[('driver', 'پیشران\u200cها (متغیرهای مستقل)'), ('relay', 'دوجانبه (سیاست\u200cگذاری)'), ('watch', 'خنثی (خودمتصل)'), ('resultant', 'رصد و دیده\u200cبانی (وابسته)')], max_length=12, verbose_name='ناحیه'),
        ),
        migrations.AlterField(
            model_name='towsstrategy',
            name='text',
            field=models.TextField(verbose_name='متن راهبرد'),
        ),
    ]
