# Generated by Django 5.2.15 on 2026-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0037_alter_crossimpactfactor_quadrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='domain',
            field=models.CharField(blank=True, max_length=100, verbose_name='حوزه'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='expectation_flag',
            field=models.BooleanField(default=False, verbose_name='نوع: انتظار'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='need_flag',
            field=models.BooleanField(default=False, verbose_name='نوع: نیاز'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='opportunity_impact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز تأثیر فرصت'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='opportunity_importance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز اهمیت فرصت'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='risk_detection',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قابلیت تشخیص ریسک'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='risk_occurrence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='احتمال وقوع ریسک'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='risk_severity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شدت ریسک'),
        ),
    ]
