# Generated by Django 5.2.15 on 2026-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0038_stakeholder_domain_stakeholder_expectation_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='الزامات قانونی و سازمانی')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='مأخذ الزام')),
                ('is_legal', models.BooleanField(default=False, verbose_name='قانونی')),
                ('is_organizational', models.BooleanField(default=False, verbose_name='سازمانی')),
                ('revision_date', models.CharField(blank=True, max_length=40, verbose_name='تاریخ ویرایش الزام')),
                ('related_documents', models.TextField(blank=True, verbose_name='مستندات داخلی مرتبط')),
                ('scope', models.CharField(blank=True, max_length=300, verbose_name='محل کاربرد')),
                ('risk_text', models.TextField(blank=True, verbose_name='ریسک')),
                ('opportunity_text', models.TextField(blank=True, verbose_name='فرصت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='نام مدیریت/معاونت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الزام قانونی',
                'verbose_name_plural': 'بانک الزامات قانونی',
                'ordering': ['department', 'title'],
            },
        ),
    ]
