# Generated by Django 5.2.15 on 2026-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0039_legalrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ردیف اصلی')),
                ('category', models.CharField(max_length=150, verbose_name='دسته\u200cبندی محیط')),
                ('factor_text', models.CharField(max_length=400, verbose_name='شرح عامل تأثیرگذار')),
                ('detail', models.TextField(blank=True, verbose_name='توضیح تفصیلی (راهنمای درک و امتیازدهی)')),
                ('effect_type', models.CharField(blank=True, max_length=30, verbose_name='نوع اثر')),
                ('scoring_guide', models.CharField(blank=True, max_length=300, verbose_name='راهنمای امتیازدهی')),
                ('avg_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='میانگین امتیاز')),
                ('freq_high', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فراوانی اثر بالا (۷-۸)')),
                ('freq_very_high', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فراوانی اثر بسیار بالا (۹-۱۰)')),
                ('freq_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='جمع فراوانی اثرهای بالا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عامل محیطی',
                'verbose_name_plural': 'بانک عوامل محیطی',
                'ordering': ['-avg_score', 'order'],
            },
        ),
    ]
