# Generated by Django 5.2.15 on 2026-08-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0040_environmentalfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='source_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='strategic.companykpi', verbose_name='شکاف شاخص مبنا (اختیاری)'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='source_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='strategic.risk', verbose_name='ریسک مبنا (اختیاری)'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='source_tows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='strategic.towsstrategy', verbose_name='راهبرد TOWS مبنا (اختیاری)'),
        ),
    ]
