# Generated by Django 5.2.15 on 2026-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0041_initiative_source_kpi_initiative_source_risk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='source_kpi',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='source_risk',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='source_tows',
        ),
        migrations.AddField(
            model_name='initiative',
            name='source_kpi',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='strategic.companykpi', verbose_name='شکاف\u200cهای شاخص مبنا (اختیاری)'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='source_risk',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='strategic.risk', verbose_name='ریسک\u200cهای مبنا (اختیاری)'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='source_tows',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='strategic.towsstrategy', verbose_name='راهبردهای TOWS مبنا (اختیاری)'),
        ),
    ]
