# Generated by Django 5.2.15 on 2026-08-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0042_remove_initiative_source_kpi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicobjective',
            name='linked_company_kpis',
        ),
    ]
