# Generated by Django 5.2.15 on 2026-08-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0043_remove_strategicobjective_linked_company_kpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossimpactfactor',
            name='linked_porter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_impact_factors', to='strategic.porterforce', verbose_name='نیروی پورتر مرتبط (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='source_kpi',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='strategic.companykpi', verbose_name='شاخص\u200cهای مبنا (اختیاری)'),
        ),
    ]
