# Generated by Django 5.2.15 on 2026-08-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0044_crossimpactfactor_linked_porter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgvalue',
            name='color',
            field=models.CharField(blank=True, choices=[('#F59E0B', 'کهربایی'), ('#EC4899', 'صورتی'), ('#8B5CF6', 'بنفش'), ('#0EA5E9', 'آبی'), ('#F43F5E', 'قرمز مرجانی'), ('#EAB308', 'زرد طلایی'), ('#22C55E', 'سبز'), ('#A8321E', 'قرمز آجری (مرکز)')], default='#C97A2B', max_length=20, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='orgvalue',
            name='definition',
            field=models.TextField(blank=True, verbose_name='تعریف'),
        ),
        migrations.AddField(
            model_name='orgvalue',
            name='examples',
            field=models.TextField(blank=True, verbose_name='نمونه\u200cهای اجرایی در سازمان (هر خط یک نمونه)'),
        ),
        migrations.AddField(
            model_name='orgvalue',
            name='expected_behaviors',
            field=models.TextField(blank=True, verbose_name='رفتارهای مورد انتظار (هر خط یک رفتار)'),
        ),
        migrations.AddField(
            model_name='orgvalue',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-trophy', 'جام (رقابت/دستاورد)'), ('fa-solid fa-handshake', 'دست\u200cدادن (اعتماد/شفافیت)'), ('fa-solid fa-shield-halved', 'سپر (کرامت/حفاظت از حقوق)'), ('fa-solid fa-bullhorn', 'بلندگو (اطلاع\u200cرسانی)'), ('fa-solid fa-people-group', 'گروه افراد (کارتیمی/کارکنان)'), ('fa-solid fa-lightbulb', 'لامپ (نوآوری)'), ('fa-solid fa-users', 'کاربران (وحدت/مشتری)'), ('fa-solid fa-heart', 'قلب (مشتری\u200cمداری)'), ('fa-solid fa-graduation-cap', 'کلاه فارغ\u200cالتحصیلی (آموزش/توسعه)'), ('fa-solid fa-compass', 'قطب\u200cنما (جهت\u200cگیری)'), ('fa-solid fa-star', 'ستاره (پیش\u200cفرض)')], default='fa-solid fa-star', max_length=40, verbose_name='آیکون'),
        ),
    ]
