# Generated by Django 5.2.15 on 2026-08-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0045_orgvalue_color_orgvalue_definition_orgvalue_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgvalue',
            name='related_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_values', to='strategic.qualitypolicypoint', verbose_name='بند خط\u200cمشی مرتبط'),
        ),
    ]
