# Generated by Django 5.2.15 on 2026-08-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0046_orgvalue_related_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgidentity',
            name='management_statement',
            field=models.TextField(blank=True, verbose_name='پیام مدیریت ارشد (بالای امضا)'),
        ),
    ]
