# Generated by Django 5.2.15 on 2026-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0047_orgidentity_management_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrequirement',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='برون سازمانی'),
        ),
        migrations.AddField(
            model_name='legalrequirement',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='درون سازمانی'),
        ),
    ]
