# Generated by Django 5.2.15 on 2026-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0048_legalrequirement_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestelfactor',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='توضیح تفصیلی (راهنمای درک و امتیازدهی)'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('opportunity', 'فرصت'), ('threat', 'تهدید'), ('both', 'فرصت/تهدید')], max_length=15, verbose_name='نوع اثر'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='related_standard',
            field=models.CharField(blank=True, max_length=150, verbose_name='استاندارد مرتبط'),
        ),
        migrations.AddField(
            model_name='pestelfactor',
            name='scoring_guide',
            field=models.TextField(blank=True, verbose_name='راهنمای امتیازدهی'),
        ),
    ]
