# Generated by Django 5.2.15 on 2026-08-06 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0049_pestelfactor_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porterforce',
            options={'ordering': ['force', 'order'], 'verbose_name': 'عامل پورتر', 'verbose_name_plural': 'تحلیل پنج نیروی پورتر'},
        ),
        migrations.RemoveField(
            model_name='porterforce',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='porterforce',
            name='level',
        ),
        migrations.RemoveField(
            model_name='porterforce',
            name='reasons',
        ),
        migrations.RemoveField(
            model_name='porterforce',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='porterforce',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='توضیح تفصیلی (راهنمای درک و امتیازدهی)'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('opportunity', 'فرصت'), ('threat', 'تهدید'), ('both', 'فرصت/تهدید')], max_length=15, verbose_name='نوع اثر'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='horizon',
            field=models.CharField(choices=[('short', 'کوتاه\u200cمدت'), ('medium', 'میان\u200cمدت'), ('long', 'بلندمدت')], default='medium', max_length=10, verbose_name='افق زمانی'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='impact_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='میزان اثر'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='probability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='احتمال وقوع'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='related_standard',
            field=models.CharField(blank=True, max_length=150, verbose_name='استاندارد مرتبط'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='scoring_guide',
            field=models.TextField(blank=True, verbose_name='راهنمای امتیازدهی'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='متن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porterforce',
            name='trend',
            field=models.CharField(choices=[('up', 'صعودی'), ('down', 'نزولی'), ('flat', 'ثابت')], default='flat', max_length=10, verbose_name='روند تغییر'),
        ),
        migrations.AddField(
            model_name='porterforce',
            name='uncertainty',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='میزان عدم\u200cقطعیت'),
        ),
        migrations.AlterField(
            model_name='porterforce',
            name='force',
            field=models.CharField(choices=[('rivalry', 'قدرت رقبای موجود'), ('buyer_power', 'قدرت چانه\u200cزنی خریداران'), ('supplier_power', 'قدرت چانه\u200cزنی تأمین\u200cکنندگان'), ('new_entrants', 'تهدید تازه\u200cواردان'), ('substitutes', 'تهدید کالاها/خدمات جایگزین')], max_length=20, verbose_name='نیروی رقابتی'),
        ),
    ]
