# Generated by Django 5.2.15 on 2026-08-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0050_alter_porterforce_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='برون سازمانی'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='درون سازمانی'),
        ),
    ]
