# Generated by Django 5.2.15 on 2026-08-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0051_stakeholder_is_external_stakeholder_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='related_porter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_stakeholders', to='strategic.porterforce', verbose_name='عامل Porter مرتبط'),
        ),
    ]
