# Generated by Django 5.2.15 on 2026-08-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0052_stakeholder_related_porter'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrequirement',
            name='related_pestel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_legal_requirements', to='strategic.pestelfactor', verbose_name='عامل PESTEL مرتبط'),
        ),
    ]
