# Generated by Django 5.2.15 on 2026-08-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0053_legalrequirement_related_pestel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='related_porter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_stakeholders_old_tmp', to='strategic.porterforce', verbose_name='عامل Porter مرتبط'),
        ),
    ]
