# Generated by Django 5.2.15 on 2026-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0054_alter_stakeholder_related_porter'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='related_porters',
            field=models.ManyToManyField(blank=True, related_name='linked_stakeholders', to='strategic.porterforce', verbose_name='عوامل Porter مرتبط'),
        ),
    ]
