# Generated by Django 5.2.15 on 2026-08-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0056_copy_related_porter_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='related_porter',
        ),
    ]
