# Generated by Django 5.2.15 on 2026-08-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0057_remove_stakeholder_related_porter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestelfactor',
            name='related_stakeholders',
            field=models.ManyToManyField(blank=True, related_name='linked_pestel_factors', to='strategic.stakeholder', verbose_name='ذینفعان مرتبط'),
        ),
    ]
