# Generated by Django 5.2.15 on 2026-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0058_pestelfactor_related_stakeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='related_swot_items',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__in': ['t', 'w']}, related_name='risks', to='strategic.swotitem', verbose_name='منشأ (تهدید/ضعف SWOT)'),
        ),
    ]
