# Generated by Django 5.2.15 on 2026-08-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0059_risk_related_swot_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioaxes',
            name='axis1_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategic.crossimpactfactor', verbose_name='پیشران مبنای محور عمودی (ماتریس اثر متقابل)'),
        ),
        migrations.AddField(
            model_name='scenarioaxes',
            name='axis2_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategic.crossimpactfactor', verbose_name='پیشران مبنای محور افقی (ماتریس اثر متقابل)'),
        ),
    ]
