# Generated by Django 5.2.15 on 2026-08-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0060_scenarioaxes_axis1_source_scenarioaxes_axis2_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300, verbose_name='تکه\u200cمتن انتخاب\u200cشده')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cross_impact_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_highlights', to='strategic.crossimpactfactor', verbose_name='عامل ماتریس اثر متقابل')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='strategic.scenario')),
            ],
            options={
                'verbose_name': 'برچسب متن سناریو',
                'verbose_name_plural': 'برچسب\u200cهای متن سناریو',
                'ordering': ['order'],
            },
        ),
    ]
