# Generated by Django 5.2.15 on 2026-08-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0061_scenariohighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='inherent_impact',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='inherent_likelihood',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='target_impact',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='target_likelihood',
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3, verbose_name='شدت اثر (R)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3, verbose_name='احتمال رخداد (P)'),
        ),
    ]
