# Generated by Django 5.2.15 on 2026-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0062_remove_risk_inherent_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد شاخص')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان شاخص')),
                ('unit', models.CharField(blank=True, max_length=60, verbose_name='واحد سنجش')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='دپارتمان مالک')),
                ('target_1404', models.CharField(blank=True, max_length=60, verbose_name='هدف سال ۱۴۰۴')),
                ('actual_1404', models.CharField(blank=True, max_length=60, verbose_name='عملکرد ۱۴۰۴')),
                ('target_1405', models.CharField(blank=True, max_length=60, verbose_name='هدف سال ۱۴۰۵')),
                ('actual_1405', models.CharField(blank=True, max_length=60, verbose_name='عملکرد ۱۴۰۵')),
                ('progress_1405', models.CharField(blank=True, max_length=20, verbose_name='درصد تحقق (دستی)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شاخص عملیاتی',
                'verbose_name_plural': 'شاخص\u200cهای عملیاتی',
                'ordering': ['department', 'order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='linked_operational_kpis',
            field=models.ManyToManyField(blank=True, related_name='strategic_objectives', to='strategic.operationalkpi', verbose_name='شاخص\u200cهای عملیاتی مرتبط'),
        ),
    ]
