# Generated by Django 5.2.15 on 2026-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0063_operationalkpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='source_operational_kpi',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='strategic.operationalkpi', verbose_name='شاخص\u200cهای عملیاتی مبنا (اختیاری)'),
        ),
    ]
