# Generated by Django 5.2.15 on 2026-08-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0064_initiative_source_operational_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioResponseStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن راهبرد')),
                ('related_standard', models.CharField(blank=True, max_length=100, verbose_name='استاندارد مرتبط (اختیاری)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_strategies', to='strategic.scenario', verbose_name='سناریو')),
            ],
            options={
                'verbose_name': 'راهبرد پاسخ به سناریو',
                'verbose_name_plural': 'راهبردهای پاسخ به سناریو',
                'ordering': ['order'],
            },
        ),
    ]
