# Generated by Django 5.2.15 on 2026-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0065_scenarioresponsestrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIdentifiedFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pestel', 'PESTEL'), ('porter', 'Porter')], max_length=10, verbose_name='نوع')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='معاونت/واحد پیشنهاددهنده')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='دسته\u200cبندی')),
                ('text', models.TextField(verbose_name='شرح عامل')),
                ('row_number', models.PositiveIntegerField(default=0, verbose_name='ردیف اصلی در فایل مرجع')),
            ],
            options={
                'verbose_name': 'عامل شناسایی\u200cشده اولیه (آرشیو)',
                'verbose_name_plural': 'آرشیو عوامل شناسایی\u200cشده اولیه',
                'ordering': ['source_type', 'row_number'],
            },
        ),
    ]
