# Generated by Django 5.2.15 on 2026-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0067_alter_orgvalue_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgvalue',
            name='color',
            field=models.CharField(blank=True, choices=[('#C97A2B', 'کهربایی (نارنجی ملایم)'), ('#1E6E7A', 'سرمه\u200cای فیروزه\u200cای'), ('#6C56A3', 'بنفش ملایم'), ('#2E5C8A', 'آبی سرمه\u200cای'), ('#B0413E', 'قرمز آجری روشن'), ('#D9A441', 'طلایی خاکی'), ('#3E7A52', 'سبز زیتونی'), ('#A8321E', 'قرمز آجری (مرکز)')], default='#C97A2B', max_length=20, verbose_name='رنگ'),
        ),
    ]
