# Generated by Django 5.2.15 on 2026-08-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0068_alter_orgvalue_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='related_initiatives',
            field=models.ManyToManyField(blank=True, related_name='linked_stakeholders', to='strategic.initiative', verbose_name='پروژه\u200cهای تحول مرتبط'),
        ),
    ]
