# Generated by Django 5.2.15 on 2026-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0069_stakeholder_related_initiatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalkpi',
            name='domain',
            field=models.CharField(choices=[('Q', 'کیفیت (Quality)'), ('D', 'تحویل/حجم (Delivery)'), ('C', 'هزینه/درآمد (Cost)'), ('M', 'مدیریتی (Management)')], default='Q', max_length=1, verbose_name='حوزه اثربخشی'),
        ),
    ]
