# Generated by Django 5.2.15 on 2026-08-18 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0070_operationalkpi_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='companykpi',
            name='source_operational_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to_company_kpis', to='strategic.operationalkpi', verbose_name='برگرفته از شاخص عملیاتی (اختیاری)'),
        ),
    ]
