# Generated by Django 5.2.15 on 2026-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0071_companykpi_source_operational_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='division',
            field=models.CharField(blank=True, max_length=150, verbose_name='معاونت'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='work_group',
            field=models.CharField(blank=True, max_length=150, verbose_name='کارگروه'),
        ),
    ]
