# Generated by Django 5.2.15 on 2026-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0072_initiative_division_initiative_work_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='کد پروژه'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال اجرا'), ('deviation', 'انحراف پروژه'), ('done', 'تکمیل\u200cشده')], default='in_progress', max_length=20, verbose_name='وضعیت'),
        ),
    ]
