# Generated by Django 5.2.15 on 2026-08-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0074_migrate_initiative_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgvalue',
            name='related_objectives',
            field=models.ManyToManyField(blank=True, related_name='linked_org_values', to='strategic.strategicobjective', verbose_name='اهداف استراتژیک مرتبط'),
        ),
    ]
