# Generated by Django 6.1 on 2026-08-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0075_orgvalue_related_objectives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('exchange_rate', 'نرخ ارز'), ('raw_material', 'مواد اولیه / قطعات وارداتی'), ('competitor', 'رقبا'), ('other', 'سایر')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('value', models.TextField(verbose_name='مقدار / توضیح')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='واحد (اختیاری)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='نام منبع')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='آدرس منبع')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت')),
                ('fetched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'رکورد هوش بازار',
                'verbose_name_plural': 'هوش بازار',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
