# Generated by Django 6.1 on 2026-08-24 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0076_marketintelrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ادمین کامل'), ('editor', 'ویرایشگر'), ('viewer', 'کارشناس (فقط مشاهده)')], default='viewer', max_length=10, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن (اختیاری)')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_users', to='strategic.businessunit', verbose_name='کسب\u200cوکار مرتبط (اختیاری)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
