# Generated by Django 6.1 on 2026-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0077_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgvalue',
            name='related_objectives',
        ),
        migrations.AddField(
            model_name='orgvalue',
            name='related_objectives',
            field=models.ManyToManyField(blank=True, related_name='linked_org_values', to='strategic.companyobjective', verbose_name='اهداف کلان مرتبط'),
        ),
    ]
