# Generated by Django 6.1 on 2026-08-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0078_remove_orgvalue_related_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='item_type',
            field=models.CharField(choices=[('project', 'پروژه'), ('action', 'اقدام')], default='project', max_length=10, verbose_name='نوع'),
        ),
    ]
