# Generated by Django 6.1 on 2026-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0079_initiative_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال اجرا'), ('deviation', 'توقف'), ('done', 'تکمیل\u200cشده')], default='in_progress', max_length=20, verbose_name='وضعیت'),
        ),
    ]
