# Generated by Django 6.1 on 2026-08-28 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0080_alter_initiative_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfactionBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('industry_avg_satisfaction', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='میانگین رضایت صنعت (٪ یا امتیاز)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع بنچمارک')),
                ('note', models.TextField(blank=True, verbose_name='توضیح (اختیاری)')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'بنچمارک رضایت مشتری صنعت',
                'verbose_name_plural': 'بنچمارک\u200cهای رضایت مشتری صنعت',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='DomesticRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='نام ماده')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قیمت داخلی (ریال)')),
                ('unit', models.CharField(max_length=30, verbose_name='واحد (کیلوگرم/تن/...)')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'قیمت ماده\u200cی اولیه\u200cی داخلی',
                'verbose_name_plural': 'قیمت مواد اولیه\u200cی داخلی',
                'ordering': ['material_name', '-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='EVTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('ev_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد خودروی برقی/هیبریدی ثبت\u200cشده')),
                ('incentive_policies', models.TextField(blank=True, verbose_name='سیاست\u200cهای تشویقی دولت')),
                ('charging_infrastructure', models.TextField(blank=True, verbose_name='وضعیت زیرساخت شارژ')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'روند خودروی برقی/هیبریدی',
                'verbose_name_plural': 'روند خودروهای برقی/هیبریدی',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=60, verbose_name='نام ارز')),
                ('value_rial', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='نرخ (ریال)')),
                ('period_date', models.DateField(verbose_name='تاریخ نرخ')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('note', models.TextField(blank=True, verbose_name='توضیح (اختیاری)')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ\u200cهای ارز',
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='InterestInflationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('inflation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ تورم نقطه\u200cبه\u200cنقطه (٪)')),
                ('bank_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ سود تسهیلات بانکی (٪)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'نرخ سود و تورم',
                'verbose_name_plural': 'نرخ\u200cهای سود بانکی و تورم',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborMarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('job_role', models.CharField(max_length=120, verbose_name='رده\u200cی شغلی')),
                ('avg_industry_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='میانگین حقوق صنعت (ریال)')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ ترک شغل صنعت (٪ اختیاری)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'آمار بازار کار صنعت',
                'verbose_name_plural': 'آمار بازار کار و دستمزد صنعت',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalTradeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الزام/محدودیت')),
                ('item_type', models.CharField(choices=[('domestic', 'داخلی'), ('international', 'بین\u200cالمللی / تحریم')], max_length=15, verbose_name='نوع')),
                ('announce_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اجرا/مهلت')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='سازمان مربوطه')),
                ('impact_level', models.CharField(choices=[('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=10, verbose_name='سطح اثر بر ما')),
                ('description', models.TextField(blank=True, verbose_name='توضیح اثر')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'الزام قانونی/تجاری',
                'verbose_name_plural': 'الزامات قانونی و تجاری',
                'ordering': ['-effective_date', '-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=80, verbose_name='کشور تأمین\u200cکننده')),
                ('status', models.CharField(choices=[('stable', 'باثبات'), ('risky', 'پرریسک'), ('sanctioned', 'تحریم/محدود')], default='stable', max_length=15, verbose_name='وضعیت سیاسی/تجاری')),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان تحویل تخمینی (روز)')),
                ('local_currency_rate', models.CharField(blank=True, max_length=100, verbose_name='نرخ ارز محلی مرتبط (اختیاری)')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'شرایط تأمین\u200cکننده\u200cی بین\u200cالمللی',
                'verbose_name_plural': 'شرایط تأمین\u200cکنندگان بین\u200cالمللی',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره (مثلاً مرداد ۱۴۰۵)')),
                ('total_production', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تولید کل کشور')),
                ('total_sales', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد فروش کل کشور')),
                ('brand_breakdown', models.TextField(blank=True, verbose_name='تفکیک برند (اختیاری)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'آمار بازار خودرو کشور',
                'verbose_name_plural': 'آمار تولید و فروش خودرو کشور',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.DeleteModel(
            name='MarketIntelRecord',
        ),
    ]
