# Generated by Django 6.1 on 2026-08-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0081_customersatisfactionbenchmark_domesticrawmaterial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercondition',
            options={'ordering': ['supplier_type', 'country'], 'verbose_name': 'شرایط تأمین\u200cکننده', 'verbose_name_plural': 'شرایط تأمین\u200cکنندگان'},
        ),
        migrations.AddField(
            model_name='suppliercondition',
            name='supplier_type',
            field=models.CharField(choices=[('domestic', 'داخلی'), ('international', 'بین\u200cالمللی')], default='international', max_length=15, verbose_name='نوع تأمین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='suppliercondition',
            name='country',
            field=models.CharField(max_length=80, verbose_name='کشور/منطقه\u200cی تأمین\u200cکننده'),
        ),
    ]
