# Generated by Django 6.1 on 2026-08-28 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0082_alter_suppliercondition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticrawmaterial',
            name='monthly_fluctuation_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ نوسان ماهانه (٪ اختیاری)'),
        ),
        migrations.AddField(
            model_name='domesticrawmaterial',
            name='usage_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع کاربرد (اختیاری)'),
        ),
        migrations.CreateModel(
            name='StrategicElectronicPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150, verbose_name='نام قطعه')),
                ('global_inventory_note', models.TextField(blank=True, verbose_name='وضعیت موجودی انبار جهانی')),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان تحویل (روز)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت (دلار)')),
                ('status', models.CharField(choices=[('normal', 'عادی'), ('limited', 'محدود'), ('critical', 'بحرانی')], default='normal', max_length=10, verbose_name='وضعیت')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'وضعیت قطعه\u200cی راهبردی/الکترونیک',
                'verbose_name_plural': 'قطعات راهبردی و الکترونیک',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLoanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نرخ سود وام خودرو (٪)')),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='حداکثر مبلغ وام (ریال)')),
                ('mandatory_down_payment_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='پیش\u200cپرداخت اجباری (٪)')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'نرخ تسهیلات خرید خودرو',
                'verbose_name_plural': 'نرخ\u200cهای تسهیلات خرید خودرو',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePartsTradeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره')),
                ('imported_vehicle_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد خودروی وارداتی')),
                ('parts_import_value', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='ارزش واردات قطعات (دلار)')),
                ('parts_export_value', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True, verbose_name='ارزش صادرات قطعات (دلار)')),
                ('origin_destination', models.CharField(blank=True, max_length=150, verbose_name='کشور مبدأ/مقصد عمده')),
                ('source_name', models.CharField(blank=True, max_length=150, verbose_name='منبع')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'آمار واردات/صادرات قطعات و خودرو',
                'verbose_name_plural': 'آمار واردات/صادرات قطعات و خودرو',
                'ordering': ['-entered_at'],
            },
        ),
    ]
