# Generated by Django 6.1 on 2026-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0083_domesticrawmaterial_monthly_fluctuation_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersatisfactionbenchmark',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='domesticrawmaterial',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='evtrend',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='interestinflationrate',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='labormarketstat',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='legaltraderequirement',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='strategicelectronicpart',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='suppliercondition',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='vehicleloanrate',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='vehiclemarketstat',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
        migrations.AddField(
            model_name='vehiclepartstradestat',
            name='analyst_note',
            field=models.TextField(blank=True, verbose_name='تحلیل/برداشت کارشناس'),
        ),
    ]
