# Generated by Django 6.1 on 2026-08-28 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0084_customersatisfactionbenchmark_analyst_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان گزارش')),
                ('period_label', models.CharField(max_length=40, verbose_name='دوره (مثلاً مرداد ۱۴۰۵)')),
                ('report_date', models.DateField(verbose_name='تاریخ تهیه\u200cی گزارش')),
                ('summary', models.TextField(verbose_name='خلاصه\u200cی اجرایی')),
                ('content', models.TextField(verbose_name='متن کامل تحلیل')),
                ('key_risks', models.TextField(blank=True, verbose_name='ریسک\u200cهای کلیدی این دوره (اختیاری)')),
                ('key_opportunities', models.TextField(blank=True, verbose_name='فرصت\u200cهای کلیدی این دوره (اختیاری)')),
                ('recommended_actions', models.TextField(blank=True, verbose_name='اقدامات پیشنهادی (اختیاری)')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تهیه\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'گزارش تحلیلی دوره\u200cای',
                'verbose_name_plural': 'گزارش\u200cهای تحلیلی دوره\u200cای',
                'ordering': ['-report_date'],
            },
        ),
    ]
