# Generated by Django 5.2.15 on 2026-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0085_marketintelreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='شرح')),
                ('finding_type', models.CharField(choices=[('strength', 'نقاط قوت'), ('nonconformity', 'عدم انطباق'), ('improvement', 'توصیه بهبود')], default='nonconformity', max_length=20, verbose_name='نوع')),
                ('standard', models.CharField(blank=True, max_length=200, verbose_name='استاندارد مرتبط')),
                ('owner', models.CharField(blank=True, max_length=200, verbose_name='مالک')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سال')),
                ('audit_period', models.CharField(blank=True, choices=[('farvardin', 'فروردین'), ('ordibehesht', 'اردیبهشت'), ('khordad', 'خرداد'), ('tir', 'تیر'), ('mordad', 'مرداد'), ('shahrivar', 'شهریور'), ('mehr', 'مهر'), ('aban', 'آبان'), ('azar', 'آذر'), ('dey', 'دی'), ('bahman', 'بهمن'), ('esfand', 'اسفند')], max_length=20, verbose_name='دوره ممیزی')),
                ('corrective_action', models.TextField(blank=True, verbose_name='اقدام اصلاحی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نتیجه ممیزی',
                'verbose_name_plural': 'نتایج ممیزی\u200cها',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
