# Generated by Django 5.2.15 on 2026-09-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0086_auditfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='related_initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='strategic.initiative', verbose_name='پروژه/اقدام اصلاحی مرتبط (اختیاری)'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='related_legal_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='strategic.legalrequirement', verbose_name='الزام قانونی مرتبط (اختیاری)'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='related_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='strategic.risk', verbose_name='ریسک مرتبط (اختیاری)'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='related_swot_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'w'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='strategic.swotitem', verbose_name='نقطه\u200cضعف SWOT مرتبط (اختیاری)'),
        ),
    ]
