# Generated by Django 5.2.15 on 2026-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0090_auditfinding_fk_to_m2m_step3_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditfinding',
            name='related_risk',
        ),
        migrations.RemoveField(
            model_name='auditfinding',
            name='related_swot_item',
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='executor',
            field=models.CharField(blank=True, max_length=200, verbose_name='مجری فرآیند'),
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='related_initiative',
            field=models.ManyToManyField(blank=True, related_name='audit_findings', to='strategic.initiative', verbose_name='پروژه\u200cها/اقدامات اصلاحی مرتبط (اختیاری)'),
        ),
    ]
