# Generated by Django 5.2.15 on 2026-09-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0091_remove_auditfinding_related_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalkpi',
            name='actual_month',
            field=models.CharField(blank=True, max_length=60, verbose_name='عملکرد ماه جاری'),
        ),
        migrations.AddField(
            model_name='operationalkpi',
            name='target_month',
            field=models.CharField(blank=True, max_length=60, verbose_name='هدف ماه جاری'),
        ),
        migrations.AlterField(
            model_name='operationalkpi',
            name='actual_1404',
            field=models.CharField(blank=True, max_length=60, verbose_name='عملکرد ۱۴۰۴ (تجمعی)'),
        ),
        migrations.AlterField(
            model_name='operationalkpi',
            name='actual_1405',
            field=models.CharField(blank=True, max_length=60, verbose_name='عملکرد ۱۴۰۵ (تجمعی)'),
        ),
        migrations.AlterField(
            model_name='operationalkpi',
            name='target_1404',
            field=models.CharField(blank=True, max_length=60, verbose_name='هدف سال ۱۴۰۴ (تجمعی)'),
        ),
        migrations.AlterField(
            model_name='operationalkpi',
            name='target_1405',
            field=models.CharField(blank=True, max_length=60, verbose_name='هدف سال ۱۴۰۵ (تجمعی)'),
        ),
    ]
