# Generated by Django 5.2.15 on 2026-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0092_operationalkpi_actual_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalkpi',
            name='is_confidential',
            field=models.BooleanField(default=False, verbose_name='محرمانه (هدف/عملکرد سالانه برای کاربر مهمان مخفی شود)'),
        ),
    ]
