# Generated by Django 5.2.15 on 2026-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic", "0098_build_venture_strategic_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalkpi",
            name="progress_month",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="درصد تحقق ماه جاری (دستی)"
            ),
        ),
    ]
