# Generated by Django 5.2.15 on 2026-09-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic", "0099_add_operational_kpi_progress_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalKPITrendPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=4, verbose_name="سال (شمسی)")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "فروردین"),
                            (2, "اردیبهشت"),
                            (3, "خرداد"),
                            (4, "تیر"),
                            (5, "مرداد"),
                            (6, "شهریور"),
                            (7, "مهر"),
                            (8, "آبان"),
                            (9, "آذر"),
                            (10, "دی"),
                            (11, "بهمن"),
                            (12, "اسفند"),
                        ],
                        verbose_name="ماه",
                    ),
                ),
                (
                    "target",
                    models.CharField(blank=True, max_length=60, verbose_name="هدف"),
                ),
                (
                    "actual",
                    models.CharField(blank=True, max_length=60, verbose_name="عملکرد"),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_points",
                        to="strategic.operationalkpi",
                        verbose_name="شاخص عملیاتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "داده روند شاخص عملیاتی",
                "verbose_name_plural": "داده\u200cهای روند شاخص\u200cهای عملیاتی",
                "ordering": ["kpi", "year", "month"],
                "unique_together": {("kpi", "year", "month")},
            },
        ),
    ]
