# Generated by Django 5.2.15 on 2026-09-29 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic", "0100_operationalkpitrendpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionalStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_key",
                    models.CharField(
                        choices=[
                            ("hq", "مدیریت\u200cهای مستقل"),
                            ("hr", "معاونت توسعه منابع انسانی و پشتیبانی"),
                            ("plan", "معاونت طرح و برنامه"),
                            ("fin", "معاونت مالی و اقتصادی"),
                            ("log", "معاونت برنامه\u200cریزی و لجستیک"),
                            ("parts", "معاونت بازرگانی قطعات"),
                            ("biz", "معاونت توسعه کسب\u200cوکار و بازار"),
                            ("service", "معاونت خدمات پس از فروش"),
                            ("eng", "معاونت مهندسی و کیفیت"),
                        ],
                        max_length=10,
                        verbose_name="معاونت / واحد سازمانی",
                    ),
                ),
                ("management", models.CharField(max_length=200, verbose_name="مدیریت")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب در مدیریت"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=400, verbose_name="عنوان استراتژی وظیفه\u200cای"
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, verbose_name="شرح (اقدام / فرآیند / نتیجه)"
                    ),
                ),
                (
                    "business_unit_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کسب\u200cوکار مرتبط"
                    ),
                ),
                (
                    "objective_text",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="هدف بالادستی (متن اصلی فایل)",
                    ),
                ),
                ("basis", models.TextField(blank=True, verbose_name="مبنا / استناد")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="functional_strategies",
                        to="strategic.strategicobjective",
                        verbose_name="اهداف نقشه استراتژیک مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "استراتژی وظیفه\u200cای",
                "verbose_name_plural": "استراتژی\u200cهای وظیفه\u200cای",
                "ordering": ["group_key", "management", "order"],
            },
        ),
    ]
