# Generated by Django 5.2.15 on 2026-09-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic", "0101_functionalstrategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="نام"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "ceo_direct",
                                "مدیریت مستقل (زیرمجموعه\u200cی مستقیم مدیرعامل)",
                            ),
                            ("deputy", "معاونت"),
                        ],
                        default="deputy",
                        max_length=12,
                        verbose_name="نوع واحد",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش (راست به چپ)"
                    ),
                ),
            ],
            options={
                "verbose_name": "واحد سطح بالای چارت سازمانی",
                "verbose_name_plural": "واحدهای سطح بالای چارت سازمانی (مدیریت\u200cهای مستقل / معاونت\u200cها)",
                "ordering": ["kind", "order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="functionalstrategy",
            options={
                "ordering": ["org_unit", "management", "order"],
                "verbose_name": "استراتژی وظیفه\u200cای",
                "verbose_name_plural": "استراتژی\u200cهای وظیفه\u200cای",
            },
        ),
        migrations.AddField(
            model_name="functionalstrategy",
            name="business_units",
            field=models.ManyToManyField(
                blank=True,
                related_name="functional_strategies",
                to="strategic.businessunit",
                verbose_name="کسب\u200cوکار مرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="functionalstrategy",
            name="business_unit_text",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="کسب\u200cوکار مرتبط (متن اصلی فایل، قدیمی)",
            ),
        ),
        migrations.AlterField(
            model_name="functionalstrategy",
            name="group_key",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="کد قدیمی معاونت (منسوخ)"
            ),
        ),
        migrations.AlterField(
            model_name="functionalstrategy",
            name="objective_text",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="هدف بالادستی (متن اصلی فایل، قدیمی)",
            ),
        ),
        migrations.AddField(
            model_name="functionalstrategy",
            name="org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="functional_strategies",
                to="strategic.orgunit",
                verbose_name="معاونت / واحد سازمانی",
            ),
        ),
    ]
