# Generated by Django 5.2.15 on 2026-09-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic", "0105_remove_functionalstrategy_business_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="کلید بخش"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="عنوان نمایشی"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="نمایش برای کاربر مهمان (بدون ورود)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
            ],
            options={
                "verbose_name": "دسترسی عمومی بخش",
                "verbose_name_plural": "تنظیمات دسترسی عمومی بخش\u200cها",
                "ordering": ["label"],
            },
        ),
    ]
